[package]
name = "clam-lang"
version = "0.1.0"

[dependencies]
clam_parser = { path = "parser" }
clam_common = { path = "common" }

[workspace]
members = [
    "parser",
    "common",
    "interpreter"
]
