[package]
name = "clam_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.2"
maplit = "1.0.2"
clam_common  = { path = "../common" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lexer_bench"
harness = false
