[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clam_common  = { path = "../common" }
derive_more = "0.99.17"
ordered-float = "3.7.0"
im = "15.1.0"
num-traits = "0.2"
